services:
  - type: web
    name: sago-web-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com
